<?php

namespace app\modules\api\controllers;

use yii\rest\ActiveController;

class DefaultController extends ActiveController
{
    public $modelClass = 'app\models\Noticias';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub

//        REMOVENDO ALGUMA AÇÃO DA API
        unset($actions['delete'], $actions['create']);

        return $actions;
    }
}
